version: '3'
services:
  apache:
    build: .docker/apache
    container_name: apache
    ports:
      - 80:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot
    environment:
      - PHP_IDE_CONFIG="serverName=DockerApp"
      - XDEBUG_CONFIG="remote_host=10.254.254.254 remote_port=9001"
    depends_on:
      - php

  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: db_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  php:
    build: .docker/php
    container_name: php
    volumes:
      - .:/home/wwwroot
    environment:
      - maildev_host=maildev
      - DATABASE_URL=mysql://root:root@mysql:3306/productService?serverVersion=8
    depends_on:
      - maildev
      - mysql
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    ports:
      - 8001:80